//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marble.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMARBLEEntities : DbContext
    {
        public DBMARBLEEntities()
            : base("name=DBMARBLEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_contactus> tbl_contactus { get; set; }
        public virtual DbSet<tbl_in> tbl_in { get; set; }
        public virtual DbSet<tbl_out> tbl_out { get; set; }
        public virtual DbSet<tbl_pic> tbl_pic { get; set; }
        public virtual DbSet<tbl_products> tbl_products { get; set; }
        public virtual DbSet<tbl_login> tbl_login { get; set; }
    }
}
