//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marble.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        public int productid { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public Nullable<double> quantity { get; set; }
        public string date { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string size { get; set; }
        public string uom { get; set; }
    }
}
