//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marble.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_out
    {
        public int id { get; set; }
        public string itemname { get; set; }
        public string itemdescription { get; set; }
        public Nullable<double> quantity { get; set; }
        public string size { get; set; }
        public string billno { get; set; }
        public string partyname { get; set; }
        public string mobile { get; set; }
        public Nullable<int> itemid { get; set; }
        public string date { get; set; }
    }
}
